# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Check if files changed
        run: |
          if [ -z $($data_changed | tr -d ' ') ]; then
            echo "exiting=true" >> GITHUB_ENV
          fi

      # Runs a set of commands using the runners shell
      - name: Embedd changed files
        if: env.exiting != 'true'
        run: |
          # TODO run embedding script

      - name: Clean up changed files variable
        if: env.exiting != 'true'
        env:
          GH_TOKEN: ${{ secrets.PULL_DOCU_TOKEN }}
        run: |
          gh variable set DATA_CHANGED_REPO --body " " 
